[project]
name = "mae5110"
version = "0.1.0"
description = "Course exercises for MAE 5110"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jax>=0.11.1",
    "matplotlib",
    "numpy",
    "ruff",
    "tqdm>=4.70.0",
]

[project.optional-dependencies]
gpu = [
    "jax[cuda13]>=0.11.1",
]

[dependency-groups]
dev = [
    "pytest",
]
